# -*- coding: utf-8 -*-
"""Taslk1.2 A and B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lq0y7niWGU3OB9XVMwk3X_If2yYBZEVT
"""

my_favorite_songs

"""A. my favorite 
songs 
"""

my_favorite_songs = [
    ['Waste a Moment', 3.03],
    ['New Salvation', 4.02],
    ['Staying\' Alive', 3.40],
    ['Out of Touch', 3.03],
    ['A Sorta Fairytale', 5.28],
    ['Easy', 4.15],
    ['Beautiful Day', 4.04],
    ['Nowhere to Run', 2.58],
    ['In This World', 4.02],
]

print('my_favorite_songs')

import random
my_favorite_songs = [
    ['Waste a Moment', 3.03],
    ['New Salvation', 4.02],
    ['Staying\' Alive', 3.40],
    ['Out of Touch', 3.03],
    ['A Sorta Fairytale', 5.28],
    ['Easy', 4.15],
    ['Beautiful Day', 4.04],
    ['Nowhere to Run', 2.58],
    ['In This World', 4.02],
]



random.sample (my_favorite_songs, 3)

three_songs = my_favorite_songs[7][1] + my_favorite_songs[2][1] + my_favorite_songs[5][1]
three_songs = round(three_songs, 2)
print('Три песни звучат', three_songs)

"""B. my favorite songs dict

"""

import random

my_favorite_songs_dict = {
    'Waste a Moment': 3.03,
    'New Salvation': 4.02,
    'Staying\' Alive': 3.40,
    'Out of Touch': 3.03,
    'A Sorta Fairytale': 5.28,
    'Easy': 4.15,
    'Beautiful Day': 4.04,
    'Nowhere to Run': 2.58,
    'In This World': 4.02,
}

print('my_favorite_songs_dict')

key, value = random.choice(list(my_favorite_songs_dict.items()))
print(key, value)


key, value = random.choice(list(my_favorite_songs_dict.items()))
print(key, value)

key, value = random.choice(list(my_favorite_songs_dict.items()))
print(key, value)

another_three_songs = my_favorite_songs_dict['New Salvation'] + my_favorite_songs_dict['Waste a Moment'] + my_favorite_songs_dict['Nowhere to Run']
another_three_songs = round(another_three_songs, 2)
print('Три песни звучат', another_three_songs)